service: sms-adventure

provider:
  name: aws
  runtime: python3.7
  environment:
    SAVES_S3_BUCKET: ${self:custom.savesBucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::${self:custom.savesBucketName}/*"
        - "arn:aws:s3:::${self:custom.savesBucketName}"

package:
  exclude:
    - "**"
  include:
    - adventure/**
    - adventure_anywhere/**
    - sms_adventure/**
    - alexa_adventure/**

functions:
  sms-adventure:
    handler: sms_adventure.handler.handle_sms
    events:
      - http:
          path: /sms
          method: post
          integration: lambda
          response:
            headers:
              Content-Type: "'application/xml'"
            template: $input.path('$')
  alexa-adventure:
    handler: alexa_adventure.handler.handle
    events:
      - alexaSkill: amzn1.ask.skill.3c273e3b-01f5-4541-b693-6cebc165908e

resources:
  Resources:
    # The one resource missing here (created via console)
    # is the route53 hosted zone for smsadventure.com.
    SavesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.savesBucketName}
    DomainCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: smsadventure.com
        SubjectAlternativeNames:
          - "*.smsadventure.com"
        ValidationMethod: DNS
    WebsiteCloudfrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Origins:
            # output from sls client deploy (serverless-finch)
            - DomainName: smsadventure.com.s3-website-us-east-1.amazonaws.com
              Id: S3-smsadventure.com
              CustomOriginConfig:
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            TargetOriginId: S3-smsadventure.com
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: False
          ViewerCertificate:
            AcmCertificateArn:
              Ref: DomainCertificate
            SslSupportMethod: sni-only
          Aliases:
            - smsadventure.com
            - www.smsadventure.com

custom:
  savesBucketName: sms-adventure-saves-bucket
  client:
    bucketName: smsadventure.com
    distributionFolder: site
    errorDocument: index.html
  customDomain:
    domainName: api.smsadventure.com

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-finch
  - serverless-domain-manager
